# <font color='blue'>Data Science Academy - Matemática Para Data Science</font>

In [5]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

Versão da Linguagem Python Usada Neste Jupyter Notebook: 3.9.13


In [6]:
# Para atualizar um pacote, execute o comando abaixo no terminal ou prompt de comando:
# pip install -U nome_pacote

# Para instalar a versão exata de um pacote, execute o comando abaixo no terminal ou prompt de comando:
# !pip install nome_pacote==versão_desejada

# Depois de instalar ou atualizar o pacote, reinicie o jupyter notebook.

# Instala o pacote watermark. 
# Esse pacote é usado para gravar as versões de outros pacotes usados neste jupyter notebook.
# !pip install -q -U watermark

In [7]:
import numpy as np

## Escalares, Vetores, Matrizes e Tensores

Python é uma excelente linguagem de programação, mas ela pode ser lenta quando usada na sua forma básica. No entanto, ela permite que você acesse bibliotecas que executem código mais rápido escrito em linguagens como C. 

NumPy é uma dessas bibliotecas e fornece alternativas rápidas para operações matemáticas em Python e foi projetado para funcionar de forma eficiente com grupos de números - como matrizes.

NumPy é uma excelente biblioteca, sendo a base de quase todos os frameworks de aprendizagem de máquina em Python. 

### Tipos de Dados e Shapes

A maneira mais comum de trabalhar com números usando NumPy é através de objetos ndarray. Eles são semelhantes às listas em Python, mas podem ter qualquer número de dimensões. Além disso, o ndarray suporta operações matemáticas rápidas, o que é exatamente o que queremos.

Como você pode armazenar qualquer número de dimensões, você pode usar ndarrays para representar qualquer um dos tipos de dados: escalares, vetores, matrizes ou tensores.

### Escalares

Escalares com NumPy são mais eficientes do que em Python. Em vez dos tipos básicos em Python como int, float, etc., o NumPy permite especificar tipos mais específicos, bem como diferentes tamanhos. Então, em vez de usar int em Python, você tem acesso a tipos como uint8, int8, uint16, int16 e assim por diante, ao usar o NumPy.

Esses tipos são importantes porque todos os objetos que você cria (vetores, matrizes, tensores) acabam por armazenar escalares. E quando você cria uma matriz NumPy, você pode especificar o tipo (mas cada item na matriz deve ter o mesmo tipo). Nesse sentido, os arrays NumPy são mais como arrays C do que as listas em Python.

Se você quiser criar uma matriz NumPy que contenha um escalar, usamos a função array do NumPy:

In [8]:
s = np.array(8)

In [9]:
type(s)

numpy.ndarray

In [10]:
print(s)

8


Você ainda pode realizar matemática entre ndarrays, escalares NumPy e escalares Python normais, como veremos mais adiante.

Você pode ver o shape da matriz usando o atributo shape, conforme abaixo. Esse comando retorna um () vazio, indicando que este objeto é um escalar.

In [11]:
s.shape

()

Mesmo que os escalares estejam dentro de arrays, você ainda os usa como um escalar normal, para operações matemáticas:

In [12]:
x = s - 3

In [13]:
x

5

Se você verificar o tipo de x, vai perceber que é numpy.int64, pois você está trabalhando com tipos NumPy, e não com os tipos Python.

Mesmo os tipos escalares suportam a maioria das funções de matriz. Então você pode chamar x.shape e retornaria () porque tem zero dimensões, mesmo que não seja uma matriz. Se você tentar usar o objeto como um escalar Python normal, você obterá um erro.

In [14]:
type(x)

numpy.int32

In [15]:
x.shape

()

### Vetores

### Vetores

Para criar um vetor, você passaria uma lista Python para a função array(), assim:

In [16]:
vec = np.array([1,2,3])

In [17]:
type(vec)

numpy.ndarray

In [18]:
print(vec)

[1 2 3]


In [19]:
vec.shape 

(3,)

Ao verificar o atributo de shape do vetor, ele retornará um único número representando o comprimento unidimensional do vetor. No exemplo acima, vec.shape retorna (3,), ou seja, tem 3 elementos em uma estrutura unidimensional.

Agora que há um número, você pode ver que a forma é uma tupla com os tamanhos de cada uma das dimensões do ndarray. Para os escalares, era apenas uma tupla vazia, mas os vetores têm uma dimensão, então a tupla inclui um número e uma vírgula 

(Python não entende (3) como uma tupla com um item, por isso requer a vírgula. Documentação oficial do Python sobre Tuplas: https://docs.python.org/3/tutorial/datastructures.html#tuples-and-sequences

Você pode acessar um elemento dentro do vetor usando índices, como este abaixo (como você pode ver, em Python a indexação começa por 0 e o índice 1 representa o segundo elemento do vetor).

In [20]:
vec2 = np.array([1,2,3,4])

In [21]:
vec2.shape 

(4,)

In [22]:
vec2[3]

4

NumPy também suporta técnicas avançadas de indexação. Por exemplo, para acessar os itens do segundo elemento em diante, você usaria:

In [23]:
vec2[1:]

array([2, 3, 4])

NumPy slicing é bastante poderoso, permitindo que você acesse qualquer combinação de itens em um ndarray. Documentação oficial sobre indexação e slicing de arrays: https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html

### Matrizes

### Matrizes

Você cria matrizes usando a função de array() NumPy, exatamente como você fez com os vetores. No entanto, em vez de apenas passar uma lista, você precisa fornecer uma lista de listas, onde cada lista representa uma linha. Então, para criar uma matriz 3x3 contendo os números de um a nove, você poderia fazer isso:

In [24]:
m = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [25]:
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
type(m)

numpy.ndarray

In [27]:
m.shape

(3, 3)

Verificando o atributo shape, retorna a tupla (3, 3) para indicar que a matriz tem duas dimensões, cada dimensão com comprimento de 3 elementos.

Você pode acessar elementos de matrizes como vetores, mas usando valores de índice adicionais. Então, para encontrar o número 6 na matriz acima, você usaria:

In [28]:
m[1][2]

6

### Tensores

### Tensores

Os tensores são como vetores e matrizes, mas podem ter n dimensões. Por exemplo, para criar um tensor 3x3x2x1, você pode fazer o seguinte:

In [29]:
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
    [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])

In [30]:
print(t)

[[[[ 1]
   [ 2]]

  [[ 3]
   [ 4]]

  [[ 5]
   [ 6]]]


 [[[ 7]
   [ 8]]

  [[ 9]
   [10]]

  [[11]
   [12]]]


 [[[13]
   [14]]

  [[15]
   [16]]

  [[17]
   [17]]]]


In [31]:
t.shape

(3, 3, 2, 1)

Para acessar um elemento do tensor, usamos a indexação da mesma forma que fizemos com vetores e matrizes:

In [32]:
t[2][2][1][0]

17

### Alterando o Formato (shape)

### Alterando o Formato (shape)

Às vezes, você precisará alterar a forma de seus dados sem realmente alterar seu conteúdo. Por exemplo, você pode ter um vetor, que é unidimensional, mas precisa de uma matriz, que é bidimensional. Há duas maneiras pelas quais você pode fazer isso.

Digamos que você tenha o seguinte vetor:

In [33]:
vec = np.array([1,2,3,4])

In [34]:
print(vec)

[1 2 3 4]


In [35]:
vec.shape

(4,)

Chamando vec.shape retornaria (4,). Mas e se você quiser uma matriz 1x4? Você pode conseguir isso com a função de reshape, assim:

In [36]:
x = vec.reshape(1,4)

In [37]:
x.shape

(1, 4)

In [38]:
print(x)

[[1 2 3 4]]


A função reshape pode ser usada para outras atividades com matrizes.

## Fim