# <font color='blue'>Data Science Academy - Matemática Para Data Science</font>

In [1]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

Versão da Linguagem Python Usada Neste Jupyter Notebook: 3.9.13


In [2]:
# Para atualizar um pacote, execute o comando abaixo no terminal ou prompt de comando:
# pip install -U nome_pacote

# Para instalar a versão exata de um pacote, execute o comando abaixo no terminal ou prompt de comando:
# !pip install nome_pacote==versão_desejada

# Depois de instalar ou atualizar o pacote, reinicie o jupyter notebook.

# Instala o pacote watermark. 
# Esse pacote é usado para gravar as versões de outros pacotes usados neste jupyter notebook.
# !pip install -q -U watermark

In [3]:
import numpy as np

In [4]:
# Versões dos pacotes usados neste jupyter notebook
%reload_ext watermark
%watermark -a "Data Science Academy" --iversions

Author: Data Science Academy

numpy: 1.21.5



## Operações Element-wise com Vetores

### Primeiro, como você faria usando apenas Linguagem Python.

Suponha que você tenha uma lista de números e que você deseja adicionar 5 a cada item da lista. Sem NumPy, você pode fazer algo como isto:

In [5]:
# Lista de valores
valores = [1, 2, 3, 4, 5]

In [6]:
print(valores)

[1, 2, 3, 4, 5]


In [7]:
# Loop for para adicionar 5 a cada elemento da lista
for i in range(len(valores)):
    valores[i] += 5

In [8]:
print(valores)

[6, 7, 8, 9, 10]


Isso faz sentido, mas é muito código para escrever e é mais lento, pois é Python puro.

### Agora sim, usando NumPy

In [9]:
valores = [1,2,3,4,5]

In [10]:
type(valores)

list

In [11]:
valores = np.array(valores) + 5

In [12]:
print(valores)

[ 6  7  8  9 10]


Bem mais simples, não? Perceba que usamos a função array() para converter o objeto Python para um objeto NumPy e então realizar o cálculo.

Mas isso pode ficar ainda mais simples. NumPy oferece funções prontas para operações matemáticas como essa. Por exemplo:

In [13]:
valores = [1,2,3,4,5]

In [14]:
type(valores)

list

In [15]:
valores = np.add(valores, 5)

In [16]:
print(valores)

[ 6  7  8  9 10]


In [17]:
type(valores)

numpy.ndarray

NumPy facilita muito nosso trabalho e vários frameworks de Deep Learning se baseiam no NumPy.

Um outro exemplo de operação element-wise com escalares e objetos ndarrays. Digamos que você tenha um objeto chamado "valores" e você queira reutilizá-lo, mas primeiro você precisa definir todos os seus valores em zero. Fácil, basta multiplicar por zero e atribuir o resultado de volta ao objeto, assim:

In [18]:
valores *= 0

In [19]:
print(valores)

[0 0 0 0 0]


## Operações Element-wise com Matrizes

As mesmas funções e operadores que trabalham com escalares e matrizes também funcionam com outras dimensões. Você só precisa se certificar de que os itens que você executa a operação possuem shapes compatíveis.

In [20]:
x = np.array([[1,3],[5,7]])
print(x)

[[1 3]
 [5 7]]


In [21]:
y = np.array([[2,4],[6,8]])
print(y)

[[2 4]
 [6 8]]


In [22]:
x + y

array([[ 3,  7],
       [11, 15]])

In [23]:
x + 5

array([[ 6,  8],
       [10, 12]])

In [24]:
x + y + 5

array([[ 8, 12],
       [16, 20]])

In [25]:
x + y / 5

array([[1.4, 3.8],
       [6.2, 8.6]])

In [26]:
(x + y) / 5

array([[0.6, 1.4],
       [2.2, 3. ]])

In [27]:
x.shape

(2, 2)

In [28]:
y.shape

(2, 2)

Isso funciona porque é uma multiplicação de elementos entre duas matrizes de forma (shape) idêntica. Experimente alterar o shape de uma das matrizes e repetir a soma. Você receberá uma mensagem de erro.

## Fim