# <font color='blue'>Data Science Academy - Matemática Para Data Science</font>

In [1]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

Versão da Linguagem Python Usada Neste Jupyter Notebook: 3.9.13


In [2]:
# Para atualizar um pacote, execute o comando abaixo no terminal ou prompt de comando:
# pip install -U nome_pacote

# Para instalar a versão exata de um pacote, execute o comando abaixo no terminal ou prompt de comando:
# !pip install nome_pacote==versão_desejada

# Depois de instalar ou atualizar o pacote, reinicie o jupyter notebook.

# Instala o pacote watermark. 
# Esse pacote é usado para gravar as versões de outros pacotes usados neste jupyter notebook.
# !pip install -q -U watermark

In [3]:
# Imports
import numpy as np
import sympy as sym

## Calculando o Determinante com NumPy e SymPy

In [4]:
# Cria uma matriz 2x2
matrix = np.array([[1, 2], [3, 4]])

In [5]:
# Calcula o determinante
determinante_1 = np.linalg.det(matrix)

In [6]:
print(determinante_1)

-2.0000000000000004


In [7]:
# Cria uma matriz 2x2
matrix = sym.Matrix([[1, 2], [3, 4]])

In [8]:
# Calcula o determinante
determinante_2 = matrix.det()

In [9]:
print(determinante_2)

-2


Fómula do determinante:

Considerando uma matriz 2 x 2 com os elementos
   

In [10]:
# Cria uma matriz 2x2 de exemplo
matrix = np.array([['a', 'b'], ['c', 'd']])

In [11]:
print(matrix)

[['a' 'b']
 ['c' 'd']]


Calculamos o determinante assim:

|Det| = ad − bc

In [12]:
# Cria uma matriz 2x2
matrix = np.array([[1, 2], [3, 4]])

In [13]:
print(matrix)

[[1 2]
 [3 4]]


In [14]:
# Calculando o determinante com operações aritméticas
determinante_3 = (1 * 4) - (2 * 3)

In [15]:
determinante_3

-2

> E para matriz com 3 dimensões?

In [16]:
b = np.array([[6,1,1], [4, -2, 5], [2,8,7]]) 

In [17]:
print (b) 

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]


In [18]:
print (np.linalg.det(b))

-306.0


In [19]:
print (6*(-2*7 - 5*8) - 1*(4*7 - 5*2) + 1*(4*8 - -2*2))

-306


Fórmula para outras dimensões:

https://www.mathsisfun.com/algebra/matrix-determinant.html

## Matriz Inversa

A matriz inversa é uma matriz que, quando multiplicada por uma matriz dada, produz a matriz identidade. A matriz identidade é uma matriz quadrada com 1s na diagonal principal e 0s em todas as outras posições.

Por exemplo, se A é uma matriz quadrada e A^-1 é sua matriz inversa, então AA^-1 = A^-1A = I, onde I é a matriz identidade.

A inversa de uma matriz só existe se a matriz é não-singular, ou seja, se o determinante da matriz é diferente de zero. Matrizes singulares não possuem inversa.

Existem vários métodos para calcular a inversa de uma matriz, como a decomposição LU, a decomposição QR, e a eliminação gaussiana. Algumas bibliotecas científicas, como o NumPy, também fornecem funções para calcular a inversa de uma matriz, como a função numpy.linalg.inv().

Aqui está um exemplo de como calcular a matriz inversa de uma matriz 2x2:

In [20]:
matriz = np.array([[1, 2], [3, 4]])

In [21]:
inversa = np.linalg.inv(matriz)

In [22]:
print(inversa)

[[-2.   1. ]
 [ 1.5 -0.5]]


> Se o determinate de uma matriz é zero, ela não tem matriz inversa.

In [23]:
mat = np.array([[1, 2], [2, 4]])

In [24]:
print(np.linalg.det(mat))

0.0


In [25]:
# Observe o erro
inversa = np.linalg.inv(mat)

LinAlgError: Singular matrix

Leia o material em pdf na sequência do capítulo 6 do curso antes de prosseguir.

## Resolvendo Sistema de Equações Lineares com Eliminação Gaussiana em Python

Aqui está um exemplo de código Python que usa o pacote NumPy para escalonar uma matriz e resolver um sistema de equações lineares usando o método de eliminação gaussiana:

In [ ]:
# Define a matriz do sistema
A = np.array([[3, 2, -1], [2, -2, 4], [-1, 1/2, -1]])

In [ ]:
print(A)

In [ ]:
# Define o vetor de termos independentes
b = np.array([1, -2, 0])

In [ ]:
print(b)

In [ ]:
# Escalonamento de matriz

# Percorre a primeira linha
for i in range(A.shape[0] - 1):
    
    # Percorre a primeira linha novamente
    for j in range(i+1, A.shape[0]):
        
        # Calcula o fator
        factor = A[j, i] / A[i, i]
        
        # Aplica o fator em A
        A[j, i:] = A[j, i:] - factor * A[i, i:]
        
        # Aplica o fator em B
        b[j] = b[j] - factor * b[i]

In [ ]:
print(A)

In [ ]:
print(b)

In [ ]:
# Matriz resultante
x = np.zeros(A.shape[0])

In [ ]:
print(x)

In [ ]:
x[-1] = b[-1] / A[-1, -1]

In [ ]:
print(x)

In [ ]:
# Resolução do sistema por substituição regressiva

# Loop pelo shape
for i in range(A.shape[0]-2, -1, -1):
    
    # Produto escalar
    x[i] = (b[i] - np.dot(A[i, i+1:], x[i+1:])) / A[i, i]

In [ ]:
# Imprime a solução
print(x)

## Fim