# <font color='blue'>Data Science Academy - Matemática Para Data Science</font>

In [5]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

Versão da Linguagem Python Usada Neste Jupyter Notebook: 3.9.13


In [6]:
# Para atualizar um pacote, execute o comando abaixo no terminal ou prompt de comando:
# pip install -U nome_pacote

# Para instalar a versão exata de um pacote, execute o comando abaixo no terminal ou prompt de comando:
# !pip install nome_pacote==versão_desejada

# Depois de instalar ou atualizar o pacote, reinicie o jupyter notebook.

# Instala o pacote watermark. 
# Esse pacote é usado para gravar as versões de outros pacotes usados neste jupyter notebook.
# !pip install -q -U watermark

In [7]:
import numpy as np

## Multiplicação de Matrizes

### Multiplicação Element-wise

Já vimos a multiplicação de matrizes com element-wise. Apenas para relembrar:

In [8]:
# Definimos uma matriz
m = np.array([[1,2,3], [4,5,6]])
print(m)

[[1 2 3]
 [4 5 6]]


In [9]:
m.shape

(2, 3)

In [10]:
# Usamos o operador de multiplicação para multiplicar cada elemento da matriz por 3. 
# Isso vai gerar uma nova matriz n.
n = m * 3
print(n)

[[ 3  6  9]
 [12 15 18]]


In [11]:
n.shape

(2, 3)

In [12]:
# Multiplicamos as duas matrizes, element-wise
matriz_resultado = m * n

In [13]:
print(matriz_resultado)

[[  3  12  27]
 [ 48  75 108]]


In [14]:
matriz_resultado.shape

(2, 3)

### MatMul x Dot

> Imagine agora que precisamos multiplicar as duas matrizes abaixo:

In [15]:
a = np.array([[1,2,3,4], [5,6,7,8]])

In [16]:
a.shape

(2, 4)

In [17]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [18]:
b.shape

(4, 3)

In [ ]:
# Essa notação é a mesma coisa que matmul()
a @ b

In [ ]:
np.matmul(a, b)

In [ ]:
np.dot(a, b)

> Porém, quando lidamos com arrays multidimensionais (N > 2) o resultado é um pouco diferente. Você pode ver a diferença abaixo.

In [ ]:
# Dois arrays de 3 dimensões cada um
a = np.random.rand(2,3,3)
b = np.random.rand(2,3,3)

In [ ]:
a.shape

In [ ]:
b.shape

In [ ]:
c = np.matmul(a, b)

In [ ]:
d = np.dot(a, b)

In [ ]:
print(c, c.shape)

In [ ]:
print(d, d.shape)

**Atenção:**

- A função matmul() usa o array como uma pilha de matrizes como elementos que residem nos dois últimos índices, respectivamente. 

- A função dot(), por outro lado, realiza a multiplicação como a soma dos produtos sobre o último eixo da primeira matriz e o penúltimo da segunda.

- Outra diferença entre matmul() e a função numpy.dot é que a função matmul() não pode realizar multiplicação de array com valores escalares.

Vamos ver mais exemplos.

### Matrix Product

https://numpy.org/doc/stable/reference/generated/numpy.matmul.html

A definição de multiplicação de matrizes indica uma multiplicação linha por coluna, onde as entradas na i-ésima linha de A são multiplicados pelas entradas correspondentes no jth coluna de B e, em seguida, somando os resultados.

A multiplicação de matrizes NÃO é comutativa.

Para encontrar o produto da matriz, você usa a função matmul() do NumPy. **O shape das matrizes precisa ser compatível.**

**Aqui estão as regras para o produto das matrizes:**

•	O número de colunas na matriz esquerda deve ser igual ao número de linhas na matriz direita (logo, a ordem das matrizes na multiplicação é importante).

•	A matriz resultante da operação possui o mesmo número de linhas que a matriz esquerda e o mesmo número de colunas que a matriz direita.

•	Ordem importa aqui. Multiplicar A • B não é o mesmo que multiplicar B • A.

•	Os dados na matriz esquerda devem ser organizados como linhas, enquanto os dados na matriz direita devem ser organizados como colunas.


In [ ]:
# Não podemos usar matmul nas matrizes do exemplo anterior pois viola uma das regras
np.matmul(m, n)

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8]])
print(a)

In [ ]:
a.shape

In [ ]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(b)

In [ ]:
b.shape

In [ ]:
# Matrix Product
matriz_reposta = np.matmul(a, b)

In [ ]:
print(matriz_reposta)

In [ ]:
matriz_reposta.shape

In [ ]:
# Se as matrizes tiverem shape incompatível, você recebe a mensagem de erro abaixo.
# Veja que A x B não é a mesma coisa que B x A na multiplicação de matrizes.
np.matmul(b, a)

### Dot Product

https://numpy.org/doc/stable/reference/generated/numpy.dot.html

O produto escalar (dot product) é a soma dos produtos dos elementos correspondentes nas duas matrizes. Para obter o produto escalar, o número de colunas da primeira matriz deve ser igual ao número de linhas da segunda matriz.

O mesmo problema do exemplo anterior aconteceria aqui devido à diferença nos shapes.

In [ ]:
np.dot(b, a)

Agora sim:

In [ ]:
np.dot(a, b)

> Dot product com escalares:

In [ ]:
# Dois escalares
k = 5
j = 7

print(np.dot(k, j))

> Dot product com vetores:

In [ ]:
# Vetores
c = [3, 4, 5]
d = [6, 7, 8]
 
print(np.dot(c, d))

> Dot product com matrizes:

In [ ]:
# Matrizes
m1 = [[2, 1], [0, 3]]
m2 = [[1, 1], [3, 2]]
 
print(np.dot(m1, m2))

> Dot product com matrizes (se inverter a ordem o resultado é diferente):

In [ ]:
print(np.dot(m2, m1))

In [ ]:
z = np.array([[1,2],[3,4]])
print(z)

In [ ]:
np.dot(z, z)

In [ ]:
# Podemos chamar a função dot() diretamente do objeto ndarray
z.dot(z) 

In [ ]:
# Matmul gera o mesmo resultado porque as dimensões são as mesmas (mesma matriz)
np.matmul(z, z)

Resumindo, o produto escalar é a soma dos produtos de valores em dois vetores de mesmo tamanho e a multiplicação de matrizes é uma versão matricial do produto escalar com duas matrizes.

## Fim