# <font color='blue'>Data Science Academy - Matemática Para Data Science</font>

In [1]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

Versão da Linguagem Python Usada Neste Jupyter Notebook: 3.9.13


In [2]:
# Para atualizar um pacote, execute o comando abaixo no terminal ou prompt de comando:
# pip install -U nome_pacote

# Para instalar a versão exata de um pacote, execute o comando abaixo no terminal ou prompt de comando:
# !pip install nome_pacote==versão_desejada

# Depois de instalar ou atualizar o pacote, reinicie o jupyter notebook.

# Instala o pacote watermark. 
# Esse pacote é usado para gravar as versões de outros pacotes usados neste jupyter notebook.
# !pip install -q -U watermark

In [3]:
# Imports
import numpy as np

## Dot Product

O produto escalar é a soma dos produtos dos elementos correspondentes nas duas matrizes. Para obter o produto escalar, o número de colunas da primeira matriz deve ser igual ao número de linhas da segunda matriz.

In [4]:
# Matrizes criadas como objetos ndarray
m = np.array([[1, 2], [3, 4]])
n = np.array([[5, 6, 7], [8, 9, 10]])

In [5]:
print(m)

[[1 2]
 [3 4]]


In [6]:
m.shape

(2, 2)

In [7]:
print(n)

[[ 5  6  7]
 [ 8  9 10]]


In [8]:
n.shape

(2, 3)

In [9]:
print(np.dot(m, n))

[[21 24 27]
 [47 54 61]]


In [10]:
# Matrizes criadas como objetos matrix
g = np.matrix([[1, 2], [3, 4]])
h = np.matrix([[5, 6, 7], [8, 9, 10]])

In [11]:
print(g)

[[1 2]
 [3 4]]


In [12]:
g.shape

(2, 2)

In [13]:
print(h)

[[ 5  6  7]
 [ 8  9 10]]


In [14]:
h.shape

(2, 3)

In [15]:
print(np.dot(g, h))

[[21 24 27]
 [47 54 61]]


## Element-wise

Ao multiplicar dois objetos ndarray usando o operador * o resultado é a multiplicação elemento por elemento. Por outro lado, ao multiplicar dois objetos do tipo matrix usando o operador * o resultado é o produto escalar que é equivalente ao np.dot() anterior.

In [16]:
# Matrizes criadas como objetos ndarray
p = np.array([[1, 2], [3, 4]])
q = np.array([[5, 6], [8, 9]])

In [17]:
type(p)

numpy.ndarray

In [18]:
type(q)

numpy.ndarray

In [19]:
print(p * q)

[[ 5 12]
 [24 36]]


In [20]:
# Matrizes criadas como objetos matrix
v = np.matrix([[1, 2], [3, 4]])
t = np.matrix([[5, 6], [8, 9]])

In [21]:
type(v)

numpy.matrix

In [22]:
type(t)

numpy.matrix

In [23]:
print(v * t)

[[21 24]
 [47 54]]


## Transposta

A transposta de uma matriz é encontrada trocando suas linhas por suas colunas. Podemos usar a função np.transpose() ou o método NumPy ndarray.transpose() ou ndarray.T (um método especial que não requer parênteses) para obter a transposição. Todos dão a mesma saída.

In [24]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [25]:
print(np.transpose(a))

[[1 3 5]
 [2 4 6]]


In [26]:
print(a.transpose())

[[1 3 5]
 [2 4 6]]


In [27]:
print(a.T)

[[1 3 5]
 [2 4 6]]


## Rank

O rank de uma matriz é a dimensão do espaço vetorial expandido (gerado) por suas colunas ou linhas. Em outras palavras, pode ser definido como o número máximo de vetores de coluna linearmente independentes ou vetores de linha.

O rank de uma matriz pode ser encontrada usando a função matrix_rank() que vem do pacote numpy.linalg.

In [28]:
z = np.arange(1, 10)

In [29]:
print(z)

[1 2 3 4 5 6 7 8 9]


In [30]:
z.shape = (3, 3)

In [31]:
print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [32]:
rank = np.linalg.matrix_rank(z)

In [33]:
print("Rank:", rank)

Rank: 2


## Determinante

O determinante de uma matriz quadrada pode ser calculado pela função det(), que também vem do pacote numpy.linalg. Se o determinante for 0, a matriz não tem inversa.

In [34]:
f = np.array([[2, 2, 1], [1, 3, 1], [1, 2, 2]])

In [35]:
print(f)

[[2 2 1]
 [1 3 1]
 [1 2 2]]


In [36]:
np.linalg.det(f)

4.999999999999999

In [37]:
np.round(np.linalg.det(f))

5.0

## Inversa da Matriz

O verdadeiro inverso de uma matriz quadrada pode ser encontrado usando a função inv() do pacote numpy.linalg. 

In [38]:
r = np.array([[2, 2, 1], [1, 3, 1], [1, 2, 2]])

In [39]:
print(r)

[[2 2 1]
 [1 3 1]
 [1 2 2]]


In [40]:
np.linalg.det(r)

4.999999999999999

In [41]:
np.linalg.inv(r)

array([[ 0.8, -0.4, -0.2],
       [-0.2,  0.6, -0.2],
       [-0.2, -0.4,  0.8]])

## Flatten

Flatten é um método simples para transformar uma matriz em uma matriz numpy unidimensional. Para isso, podemos usar o método flatten() de um objeto ndarray.

In [42]:
s = np.array([[5, 6, 7], [8, 9, 10]])

In [43]:
print(s)

[[ 5  6  7]
 [ 8  9 10]]


In [44]:
s.shape

(2, 3)

In [45]:
print(s.flatten())

[ 5  6  7  8  9 10]


## Autovalores e Autovetores

Seja A uma matriz n x n. Um escalar λ é chamado de autovalor de A se existe um vetor x diferente de zero que satisfaz a seguinte equação:

Ax = λx

O vetor x é chamado de autovetor de A correspondente a λ.

Em numpy, autovalores e autovetores podem ser calculados simultaneamente usando a função eig().

In [46]:
a = np.array([[2, 2, 1], [1, 3, 1], [1, 2, 2]])

In [47]:
w, v = np.linalg.eig(a)

In [48]:
print("Eigenvalues (Autovalores):")
print(w)

Eigenvalues (Autovalores):
[5. 1. 1.]


In [49]:
print("Eigenvectors (Autovetores):")
print(v)

Eigenvectors (Autovetores):
[[ 0.57735027  0.16903085 -0.79970556]
 [ 0.57735027 -0.50709255  0.53555105]
 [ 0.57735027  0.84515425 -0.27139654]]


O produto dos autovalores (5 x 1 x 1 = 5) é igual ao determinante (5) da mesma matriz!

Autovalores e autovetores são extremamente úteis na Análise de Componentes Principais (PCA). No PCA, os autovetores da matriz de correlação ou covariância representam os componentes principais (as direções de variância máxima) e os autovalores correspondentes representam a quantidade de variação explicada por cada componente principal. 

## Fim