# <font color='blue'>Data Science Academy - Matemática Para Data Science</font>

In [1]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

Versão da Linguagem Python Usada Neste Jupyter Notebook: 3.9.13


In [2]:
# Para atualizar um pacote, execute o comando abaixo no terminal ou prompt de comando:
# pip install -U nome_pacote

# Para instalar a versão exata de um pacote, execute o comando abaixo no terminal ou prompt de comando:
# !pip install nome_pacote==versão_desejada

# Depois de instalar ou atualizar o pacote, reinicie o jupyter notebook.

# Instala o pacote watermark. 
# Esse pacote é usado para gravar as versões de outros pacotes usados neste jupyter notebook.
# !pip install -q -U watermark

In [3]:
import numpy as np

## Transposta da Matriz

Obter a transposição de uma matriz é realmente fácil em NumPy. Basta acessar seu atributo T. Há também a função transpose() que retorna a mesma coisa, mas raramente você verá isso usado em qualquer lugar porque digitar T é muito mais fácil. 

In [4]:
m = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [5]:
print(m)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
m.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

NumPy faz isso sem realmente mover qualquer dado na memória - ele simplesmente muda a maneira como ele indexa a matriz original - por isso é bastante eficiente.

No entanto, isso também significa que você precisa ter cuidado com a forma como você modifica objetos, porque eles compartilham os mesmos dados. Por exemplo, com a mesma matriz m acima, vamos fazer uma nova variável m_t que armazene a transposição de m. Então, veja o que acontece se modificarmos um valor em m_t:

In [7]:
m_t = m.T

In [8]:
m_t[3][1] = 200

In [9]:
print(m_t)

[[  1   5   9]
 [  2   6  10]
 [  3   7  11]
 [  4 200  12]]


In [10]:
print(m)

[[  1   2   3   4]
 [  5   6   7 200]
 [  9  10  11  12]]


Observe como ele modificou a transposição e a matriz original também! Isso porque eles estão compartilhando a mesma cópia de dados. Então lembre-se de considerar a transposição apenas como uma visão diferente de sua matriz, ao invés de uma matriz diferente, inteiramente.

Ou então use o método copy().

In [11]:
m_t2 = m.T.copy()

In [12]:
m_t2[3][1] = 400

In [13]:
print(m_t2)

[[  1   5   9]
 [  2   6  10]
 [  3   7  11]
 [  4 400  12]]


In [14]:
print(m)

[[  1   2   3   4]
 [  5   6   7 200]
 [  9  10  11  12]]


### Exemplo em Redes Neurais

Digamos que você tenha as seguintes duas matrizes, chamadas inputs e pesos:

In [15]:
inputs = np.array([[-0.27,  0.45,  0.64, 0.31]])

In [16]:
print(inputs)

[[-0.27  0.45  0.64  0.31]]


In [17]:
inputs.shape

(1, 4)

In [18]:
pesos = np.array([[0.02, 0.001, -0.03, 0.036], [0.04, -0.003, 0.025, 0.009], [0.012, -0.045, 0.28, -0.067]])

In [19]:
print(pesos)

[[ 0.02   0.001 -0.03   0.036]
 [ 0.04  -0.003  0.025  0.009]
 [ 0.012 -0.045  0.28  -0.067]]


In [20]:
pesos.shape

(3, 4)

Os pesos são multiplicados aos inputs nas camadas das redes neurais, logo precisamos multiplicar pesos por inputs. Uma multiplicação de matrizes. Isso é muito fácil com o NumPy.

In [21]:
np.matmul(inputs, pesos)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

Ops, o que deu errado? Se você fez a aula de multiplicação de matrizes, então você já viu esse erro antes. As matrizes estão shapes incompatíveis porque o número de colunas na matriz esquerda, 4, não é igual ao número de linhas na matriz direita, 3.

Como resolvemos isso? Podemos usar a transposta da matriz:

In [ ]:
np.matmul(inputs, pesos.T)

Também funciona se você gerar a transposta da matriz de inputs e trocar a ordem dos parâmetros na função:

In [ ]:
np.matmul(pesos, inputs.T)

Leia o material sobre determinante no item a seguir e continuaremos no próximo vídeo.

## Fim